name: eli_player
description: Eli Player is a Flutter-based multimedia downloader that leverages yt-dlp exclusively.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  audio_session: ^0.1.19
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_linux: ^1.1.3
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  sqlite3_flutter_libs: ^0.5.20
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  http: ^1.2.1
  logger: ^2.1.0
  intl: ^0.19.0
  uuid: ^4.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/binaries/
    - assets/ffmpeg/
    - assets/images/
